<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.52">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jaekang Lee">
<meta name="dcterms.date" content="2024-11-23">
<meta name="description" content="further improve your RAG output quality using hybrid search + reranking step">

<title>How to hybrid search and rerank RAG – jaekangai-quarto</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">jaekangai-quarto</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">How to hybrid search and rerank RAG</h1>
                  <div>
        <div class="description">
          further improve your RAG output quality using hybrid search + reranking step
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">ml</div>
                <div class="quarto-category">RAG</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Jaekang Lee </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">November 23, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">0. Introduction</a>
  <ul class="collapse">
  <li><a href="#okapi-bm25-search-key-component-of-hybrid-search" id="toc-okapi-bm25-search-key-component-of-hybrid-search" class="nav-link" data-scroll-target="#okapi-bm25-search-key-component-of-hybrid-search">0.1 okapi BM25 search (Key component of hybrid search)</a></li>
  <li><a href="#cross-encoder-key-component-of-reranking" id="toc-cross-encoder-key-component-of-reranking" class="nav-link" data-scroll-target="#cross-encoder-key-component-of-reranking">0.2 Cross Encoder (Key component of reranking)</a></li>
  <li><a href="#weighted-reciprocal-rank-fusion-key-component-of-hybrid-search" id="toc-weighted-reciprocal-rank-fusion-key-component-of-hybrid-search" class="nav-link" data-scroll-target="#weighted-reciprocal-rank-fusion-key-component-of-hybrid-search">0.3 Weighted Reciprocal Rank Fusion (Key component of hybrid search)</a></li>
  </ul></li>
  <li><a href="#experiment-design" id="toc-experiment-design" class="nav-link" data-scroll-target="#experiment-design">1. Experiment design</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">2. Data</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">3. Results</a>
  <ul class="collapse">
  <li><a href="#table" id="toc-table" class="nav-link" data-scroll-target="#table">3.1 Table</a></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization">3.2 Visualization</a></li>
  <li><a href="#compute-details" id="toc-compute-details" class="nav-link" data-scroll-target="#compute-details">3.2 Compute details</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">4. Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p><img src="purple_tower.jpeg" style="width:300px;height:200px;"></p>
<hr>
<section id="introduction" class="level1">
<h1>0. Introduction</h1>
<p>Hybrid search takes advantage of lexical search and semantic search.</p>
<ul>
<li>TLDR; (Best accuracy- <strong>98.30%</strong> okapi BM25 (50% weight) + embedding vector search (50% weight))</li>
</ul>
<p>Reranking search overcomes the disadvantage of not knowing user’s query.</p>
<ul>
<li>TLDR; (Best accuracy- <strong>97.73%</strong> hybrid + reranking with CrossEncoder “cross-encoder/ms-marco-MiniLM-L-6-v2”)</li>
</ul>
<p>For comparison, the previous best accuracy was <strong>95.16%</strong> with only embedding search.</p>
<p>To understand the full experiment pipeline (This notebook builds on top of the previous components of RAG below)</p>
<ol type="1">
<li><a href="https://jaekang.quarto.pub/jaekangai-quarto/posts/2410_evaluate_rag/2024-10-20-eval-rag.html">Evaluation explanation notebook</a></li>
<li><a href="https://jaekang.quarto.pub/jaekangai-quarto/posts/2411_chunking_rag/2024-11-09-chunk-rag.html">Chunking &amp; contextualizing strategy notebook</a></li>
</ol>
<section id="okapi-bm25-search-key-component-of-hybrid-search" class="level2">
<h2 class="anchored" data-anchor-id="okapi-bm25-search-key-component-of-hybrid-search">0.1 okapi BM25 search (Key component of hybrid search)</h2>
<p>A statistical method utilizing the number of keywords and the length of documents. (Improved TF-IDF)</p>
<ul>
<li><p>first introduced in 1970 and refined (25 times, hence the 25) over time.</p></li>
<li><p>BM25 requires the following inputs:</p>
<ul>
<li><p>A search query</p></li>
<li><p>A set of documents (usually pre-retrieved by another algorithm)</p></li>
<li><p>Term frequencies in each document</p></li>
<li><p>Document lengths</p></li>
<li><p>Corpus statistics (e.g., average document length, total number of documents)</p></li>
</ul></li>
<li><p>Okapi BM25:</p>
<ul>
<li>Okapi BM25 is a variant BM25 and it was chosen for this experiment.</li>
<li><details>
<summary>
show param details
</summary>
<ul>
<li><p>k1 (Term Frequency Saturation): typically ranges from 1.2 to 2.0. Higher k1, more term repetition is favoured</p>
<ul>
<li><p>b (Length Normalization): typically ranges from 0 to 1. Higher b, shorter documents will be favoured</p></li>
<li><p>ε (Epsilon): typically very small value from 0 to 0.25. Higher ε, slightly reduces the impact of IDF for very common terms.</p></li>
</ul></li>
</ul></details></li>
</ul>

<ul>
<li><details>
<summary>
<p>show how it works</p>
</summary>
<p>Let’s say we have three books:</p>
<ol type="1">
<li><p>“Dragon Friends” (100 words long)</p></li>
<li><p>“Friendly Pets” (80 words long)</p></li>
<li><p>“Big Book of Creatures” (200 words long)</p></li>
</ol>
<p>Our search: “friendly dragons”</p>
<p>Step 1: Count words [Term Frequency Calculation]</p>
<ol type="1">
<li><p>“Dragon Friends”: “friendly” (2 times), “dragons” (5 times)</p></li>
<li><p>“Friendly Pets”: “friendly” (4 times), “dragons” (0 times)</p></li>
<li><p>“Big Book of Creatures”: “friendly” (1 time), “dragons” (2 times)</p></li>
</ol>
<p>Step 2: Check book-length [Document Length Normalization]</p>
<ol type="1">
<li><p>“Dragon Friends” is the average length</p></li>
<li><p>“Friendly Pets” is a bit shorter</p></li>
<li><p>“Big Book of Creatures” is longer</p></li>
</ol>
<p>Step 3: Special word score [Inverse Document Frequency (IDF)]</p>
<ol type="1">
<li>“dragons” gets more points because it’s in fewer books</li>
</ol>
<p>Step 4: Final score (simplified) [Scoring]</p>
<ol type="1">
<li><p>“Dragon Friends” receives the highest score</p></li>
<li><p>“Big Book of Creatures” comes second</p></li>
<li><p>“Friendly Pets” comes last (because it doesn’t have “dragons”)</p></li>
</ol>
</details></li>
</ul></li>
</ul>
</section>
<section id="cross-encoder-key-component-of-reranking" class="level2">
<h2 class="anchored" data-anchor-id="cross-encoder-key-component-of-reranking">0.2 Cross Encoder (Key component of reranking)</h2>
<p>A sentence transformer for text pair classification.</p>
<ul>
<li><p>First introduced by Microsoft Research in 2019 as part of MS MARCO project.</p></li>
<li><p>Required inputs:</p>
<ul>
<li><p>A search query</p></li>
<li><p>A candidate document/passage</p></li>
</ul></li>
<li><p>Base architecture: MiniLM-L-6 (6 layers, smaller version of BERT)</p>
<ul>
<li><p>Max sequence length: 512 tokens</p></li>
<li><p>Output: Single relevance score between 0 and 1</p></li>
<li><p>Training data: MS MARCO passage ranking dataset</p></li>
<li><p>Model size: ~80MB</p></li>
</ul></li>
<li><details>
<summary>
<p>show how it works</p>
</summary>
<p>Let’s use the same three books from BM25 example:</p>
<p>Step 1: Tokenization &amp; Input Preparation</p>
<p>Query: “friendly dragons”</p>
<p>Documents tokenized and paired with query:</p>
<ul>
<li><p>“[CLS] friendly dragons [SEP] Dragon Friends contains story…”</p>
<ul>
<li><p>“[CLS] friendly dragons [SEP] Friendly Pets discusses…”</p></li>
<li><p>“[CLS] friendly dragons [SEP] Big Book of Creatures…”</p></li>
</ul>
<p>Step 2: Contextual Understanding</p>
<ul>
<li><p>Model processes both query and document simultaneously</p></li>
<li><p>Attention mechanism allows words to interact across query and document</p></li>
<li><p>Captures semantic relationships and context</p></li>
<li><p>Understands synonyms, related concepts (e.g., “dragon” ↔︎ “serpent”)</p></li>
</ul>
<p>Step 3: Feature Extraction</p>
<ul>
<li><p>Self-attention layers process the input</p></li>
<li><p>Each layer refines the understanding</p></li>
<li><p>Captures complex patterns and relationships</p></li>
<li><p>Learns semantic similarity beyond exact matches</p></li>
</ul>
<p>Step 4: Relevance Scoring</p>
<p>Outputs single relevance score (e.g.):</p>
<ul>
<li><p>“Dragon Friends”: 0.89 (high relevance)</p></li>
<li><p>“Big Book of Creatures”: 0.72 (moderate relevance)</p></li>
<li><p>“Friendly Pets”: 0.31 (low relevance)</p></li>
</ul>
</li></ul></details></li>
</ul>

</section>
<section id="weighted-reciprocal-rank-fusion-key-component-of-hybrid-search" class="level2">
<h2 class="anchored" data-anchor-id="weighted-reciprocal-rank-fusion-key-component-of-hybrid-search">0.3 Weighted Reciprocal Rank Fusion (Key component of hybrid search)</h2>
<p>A statistical method combining multiple result sets with different relevance indicators into a single ranked list, with the ability to weight the importance of different retrieval methods.</p>
<ul>
<li><p>Best performing individual ranking methods compared to other fusion techniques like Condorcet Fuse and CombMNZ</p></li>
<li><p>Weighted RRF uses a modified formula to determine the score for ranking each document:</p></li>
</ul>
<p><span class="math display">\[ \text{score} = \sum_{q \in \text{queries}} w_q \cdot \frac{1}{k + \text{rank}(\text{result}(q), d)} \]</span></p>
<p>Where: - k is a ranking constant - q is a query in the set of queries - w_q is the weight assigned to query/method q - d is a document in the result set of q - result(q) is the result set of q - rank(result(q), d) is d’s rank within the result(q) starting from 1</p>
<ul>
<li><p>Weighted RRF allows fine-tuning of the contribution of each search method while maintaining the simplicity of the original RRF.</p></li>
<li><p>It is particularly useful for combining results from different search techniques, such as lexical search and dense vector search, when one method is known to be more reliable for certain types of queries.</p></li>
<li><details>
<summary>
<p>Show param details</p>
</summary>
<ul>
<li><p>k (Ranking Constant): typically set to a small value, such as 60. This constant helps prevent division by zero and adjusts the impact of high-ranked documents.</p></li>
<li><p>rank_window_size: determines the number of top documents from each retriever to consider for fusion.</p></li>
<li><p>weights: dictionary mapping each retrieval method to its weight (e.g., {‘vector’: 0.7, ‘lexical’: 0.3})</p></li>
</ul>
</details></li>
<li><details>
<summary>
<p>Show how it works</p>
</summary>
<p>Let’s say we have two search methods:</p>
<ol type="1">
<li>Lexical Search (weight = 0.3)</li>
<li>Semantic Search (weight = 0.7)</li>
</ol>
<p>Our search: “friendly dragons”</p>
<p>Step 1: Get rankings from each method</p>
<p>Lexical Search results:</p>
<ol type="1">
<li>“Dragon Friends”</li>
<li>“Big Book of Creatures”</li>
<li>“Friendly Pets”</li>
</ol>
<p>Semantic Search results:</p>
<ol type="1">
<li>“Friendly Pets”</li>
<li>“Dragon Friends”</li>
<li>“Big Book of Creatures”</li>
</ol>
<p>Step 2: Calculate Weighted RRF scores (using k = 1 for simplicity)</p>
<ol type="1">
<li><p>“Dragon Friends”: Score = 0.3 * 1/(1 + 1) + 0.7 * 1/(1 + 2) = 0.15 + 0.233 = 0.383</p></li>
<li><p>“Friendly Pets”: Score = 0.3 * 1/(1 + 3) + 0.7 * 1/(1 + 1) = 0.075 + 0.35 = 0.425</p></li>
<li><p>“Big Book of Creatures”: Score = 0.3 * 1/(1 + 2) + 0.7 * 1/(1 + 3) = 0.1 + 0.175 = 0.275</p></li>
</ol>
<p>Step 3: Final ranking based on Weighted RRF scores</p>
<ol type="1">
<li>“Friendly Pets” (0.425)</li>
<li>“Dragon Friends” (0.383)</li>
<li>“Big Book of Creatures” (0.275)</li>
</ol>
<p>Note how the higher weight on semantic search (0.7) caused “Friendly Pets” to rank first in the final results, whereas it would have ranked second with unweighted RRF.</p>
</details></li>
</ul>
<hr>
</section>
</section>
<section id="experiment-design" class="level1">
<h1>1. Experiment design</h1>
<p>Notice the combinations of searching and reranking strategies, I am going to use <a href="https://jaekang.quarto.pub/jaekangai-quarto/posts/2410_evaluate_rag/2024-10-20-eval-rag.html">true/false evaluation</a> to compare.</p>
<p>Following is a high level overview of the experiment, focusing on comparing which search and which reranking worked best.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="2024-11-23-rerank-rag_files/figure-html/cell-6-1-image-3.png" class="img-fluid figure-img"></p>
<figcaption>image-3.png</figcaption>
</figure>
</div>
<ol type="1">
<li>Vector Search Only
<ul>
<li>Base experiment using pure embedding vector search (Cohere-embed-v3-multilingual)</li>
<li>Returns &amp; evaluates top 3,5,10 results</li>
</ul></li>
<li>Vector + Rerank
<ul>
<li>Vector search first gets top 10 results</li>
<li>These 10 are reranked using either CrossEncoder or BM25</li>
<li>Evaluates reranked top 3,5,10 accuracy</li>
</ul></li>
<li>Hybrid Search (Top 100) + Rerank
<ul>
<li>Gets top 100 from both Vector &amp; BM25 searches</li>
<li>Merges using RRF with weights (80/20, 50/50, 20/80)</li>
<li>Further reranking with CrossEncoder</li>
<li>Evaluates final top 3,5,10 accuracy</li>
</ul></li>
</ol>
<p>Each section measures accuracy against 2,823 test queries</p>
<ul>
<li>Note that the difference between top 3,5,10 results is the amount of chunks fed to generation model before outputting true/false.</li>
</ul>
<hr>
</section>
<section id="data" class="level1">
<h1>2. Data</h1>
<p>The following bank question and answer data is used for this experiment. - <a href="https://github.com/MrJay10/banking-faq-bot/blob/master/BankFAQs.csv">FAQ_bank.csv</a> has 1764 rows of ‘Question’ and ‘Answer’ string data.</p>
<p>2865 facts were gnerated from 1764 QnAs.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><img src="2024-11-23-rerank-rag_files/figure-html/cell-10-1-image.png" class="img-fluid" alt="image.png"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Prompt: <code>"From the following context, create "+ str(n) +" many truthful facts in bullet point forms. For example: 1. Telus is a Canadian company.\n2. Toronto is city of Ontraio, Canada.\nContext:</code><code>".format(context)</code></td>
</tr>
<tr class="even">
<td style="text-align: center;">Where <code>n</code>=number of fact to generate, <code>context</code>=QnA in English</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Note that <a href="https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models?tabs=python-secure">Azure GPT4o</a> was used with <code>temperature=0.1</code></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="results" class="level1">
<h1>3. Results</h1>
<section id="table" class="level2">
<h2 class="anchored" data-anchor-id="table">3.1 Table</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 73%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Experiment</th>
<th>Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CrossEncoder reranking</td>
<td>Vector search (100%) llm_result with reranked top 3</td>
<td>94.22%</td>
</tr>
<tr class="even">
<td>CrossEncoder reranking</td>
<td>Vector search (100%) llm_result with reranked top 5</td>
<td>94.87%</td>
</tr>
<tr class="odd">
<td>CrossEncoder reranking</td>
<td>Vector search (100%) llm_result with reranked top 10</td>
<td>94.98%</td>
</tr>
<tr class="even">
<td>CrossEncoder reranking</td>
<td>Vector search (100%) llm_result with reranked top 10</td>
<td>94.98%</td>
</tr>
<tr class="odd">
<td><strong>CrossEncoder reranking</strong></td>
<td><strong>Vector search (100%) llm_result with reranked top 10</strong></td>
<td><strong>94.98%</strong></td>
</tr>
<tr class="even">
<td>BM25 reranking</td>
<td>Vector search (100%) llm_result with reranked top 3</td>
<td>93.61%</td>
</tr>
<tr class="odd">
<td>BM25 reranking</td>
<td>Vector search (100%) llm_result with reranked top 5</td>
<td>94.73%</td>
</tr>
<tr class="even">
<td>BM25 reranking</td>
<td>Vector search (100%) llm_result with reranked top 10</td>
<td><strong>95.26%</strong></td>
</tr>
<tr class="odd">
<td>Hybrid+CrossEncoder reranking</td>
<td>Vector search (80%) BM25 search (20%) RRF top 100 reranked with CrossEncoder top 3</td>
<td>97.20%</td>
</tr>
<tr class="even">
<td>Hybrid+CrossEncoder reranking</td>
<td>Vector search (80%) BM25 search (20%) RRF top 100 reranked with CrossEncoder top 5</td>
<td>97.27%</td>
</tr>
<tr class="odd">
<td>Hybrid+CrossEncoder reranking</td>
<td>Vector search (80%) BM25 search (20%) RRF top 100 reranked with CrossEncoder top 10</td>
<td>97.66%</td>
</tr>
<tr class="even">
<td>Hybrid+CrossEncoder reranking</td>
<td>Vector search (50%) BM25 search (50%) RRF top 100 reranked with CrossEncoder top 3</td>
<td>97.02%</td>
</tr>
<tr class="odd">
<td><strong>Hybrid+CrossEncoder reranking</strong></td>
<td><strong>Vector search (50%) BM25 search (50%) RRF top 100 reranked with CrossEncoder top 10</strong></td>
<td><strong>97.73%</strong></td>
</tr>
<tr class="even">
<td>Hybrid+CrossEncoder reranking</td>
<td>Vector search (20%) BM25 search (80%) RRF top 100 reranked with CrossEncoder top 3</td>
<td>97.24%</td>
</tr>
<tr class="odd">
<td>Hybrid+CrossEncoder reranking</td>
<td>Vector search (20%) BM25 search (80%) RRF top 100 reranked with CrossEncoder top 10</td>
<td>97.70%</td>
</tr>
<tr class="even">
<td>Hybrid+CrossEncoder reranking</td>
<td>Vector search (80%) BM25 search (20%) RRF top 120 reranked with CrossEncoder top 3</td>
<td>97.24%</td>
</tr>
<tr class="odd">
<td>Hybrid+CrossEncoder reranking</td>
<td>Vector search (80%) BM25 search (20%) RRF top 120 reranked with CrossEncoder top 5</td>
<td>97.38%</td>
</tr>
<tr class="even">
<td>Hybrid+CrossEncoder reranking</td>
<td>Vector search (80%) BM25 search (20%) RRF top 120 reranked with CrossEncoder top 10</td>
<td>97.27%</td>
</tr>
<tr class="odd">
<td>Hybrid</td>
<td>Vector search (80%) BM25 search (20%) RRF top 100 top 3</td>
<td>94.01%</td>
</tr>
<tr class="even">
<td>Hybrid</td>
<td>Vector search (80%) BM25 search (20%) RRF top 100 top 5</td>
<td>97.31%</td>
</tr>
<tr class="odd">
<td>Hybrid</td>
<td>Vector search (80%) BM25 search (20%) RRF top 100 top 10</td>
<td>97.48%</td>
</tr>
<tr class="even">
<td>Hybrid</td>
<td>Vector search (50%) BM25 search (50%) RRF top 100 top 3</td>
<td>97.10%</td>
</tr>
<tr class="odd">
<td>Hybrid</td>
<td>Vector search (50%) BM25 search (50%) RRF top 100 top 5</td>
<td>97.80%</td>
</tr>
<tr class="even">
<td><strong>Hybrid</strong></td>
<td><strong>Vector search (50%) BM25 search (50%) RRF top 100 top 10</strong></td>
<td><strong>98.30%</strong></td>
</tr>
<tr class="odd">
<td>Hybrid</td>
<td>Vector search (20%) BM25 search (80%) RRF top 100 top 3</td>
<td>97.34%</td>
</tr>
<tr class="even">
<td>Hybrid</td>
<td>Vector search (20%) BM25 search (80%) RRF top 100 top 5</td>
<td>97.98%</td>
</tr>
<tr class="odd">
<td>Hybrid</td>
<td>Vector search (20%) BM25 search (80%) RRF top 100 top 10</td>
<td>97.87%</td>
</tr>
</tbody>
</table>
</section>
<section id="visualization" class="level2">
<h2 class="anchored" data-anchor-id="visualization">3.2 Visualization</h2>
<div id="cell-13" class="cell">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="2024-11-23-rerank-rag_files/figure-html/cell-2-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Key Findings:
Best Overall Accuracy: 98.30% (Hybrid)
Best Non-Hybrid Accuracy: 95.26%
Average Improvement with Reranking: -0.05%
Best Vector-BM25 Ratio: 50.0% Vector, 50.0% BM25</code></pre>
</div>
</div>
<p>summary of each plot:</p>
<ol type="1">
<li>Vector-BM25 Ratio Impact (Top Left):
<ul>
<li>Performance decreases as vector search ratio increases</li>
<li>Best performance at 50% vector/50% BM25</li>
<li>Clear downward trend from 20% to 80% vector ratio</li>
</ul></li>
<li>Accuracy Distribution by Top K (Top Right):
<ul>
<li>Higher K obviously yields better accuracy (More chance that ground truth chunk is returned within top k)</li>
</ul></li>
<li>Impact of Reranking (Bottom Left):
<ul>
<li>Minimal difference between with/without reranking</li>
<li>Without reranking: 96.57%</li>
<li>With reranking: 96.52%</li>
<li>Surprisingly, reranking slightly decreases average accuracy (Perhaps the CrossEncoder model is too weak?)</li>
</ul></li>
</ol>
<div id="cell-15" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="2024-11-23-rerank-rag_files/figure-html/cell-3-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Summary of improvements from Top 3 to Top 10:
CrossEncoder: 0.76% improvement from top 3 to top 10
BM25: 1.65% improvement from top 3 to top 10
Hybrid+CrossEncoder: 0.46% improvement from top 3 to top 10
Hybrid: 3.47% improvement from top 3 to top 10

Average accuracy for each final top K:
Top 3: 94.76%
Top 5: 96.05%
Top 10: 96.34%</code></pre>
</div>
</div>
<p>Here is another interesting analysis. - obviously, more top k the better the accuracy. - observe that the jump from top 3 to top 5 is generally much more impactful than top 5 to 10, even though latter is adding 5 more chunks compared to 2 more chunk in the former.</p>
</section>
<section id="compute-details" class="level2">
<h2 class="anchored" data-anchor-id="compute-details">3.2 Compute details</h2>
<ul>
<li>CrossEncoder compute time
<ul>
<li>CPU ~ 0.244 seconds to rerank 10 chunks</li>
<li>GPU ~ 0.012 seconds to rerank 10 chunks, 0.06 seconds to rerank 100 chunks</li>
</ul></li>
<li>BM25 compute time
<ul>
<li>CPU ~ 0.006 seconds to rerank 10 chunks</li>
</ul></li>
</ul>
</section>
</section>
<section id="summary" class="level1">
<h1>4. Summary</h1>
<ul>
<li>Hybrid search with Vector search and BM25 search ratio of 50/50 + no reranking gave the highest accuracy at 98.3%</li>
<li>Surprisingly, reranking with CrossEncoder DECREASED the overall accuracy by -0.05%!</li>
<li>Surprisingly, there were instances where feeding generation model top 10 instead of top 3 actually decreased the accuracy. (See Vector search (80%) BM25 search (20%) RRF top 120 reranked with CrossEncoder top 5 vs top 10 in the table, 98.34% vs 97.27%)</li>
</ul>
<p>This is a critical finding because reranking step with CrossEncoder would have required an expensive GPU compute for production.</p>
<p>Shows us that there is no universal solution in machine learning. Every custom data must be thoroughly experimented.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = true;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>